version: 1
formatters:
  dmt_formatter:
    format: '%(asctime)s - %(filename)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: dmt_formatter
    stream: ext://sys.stdout
  file:
      class : logging.FileHandler
      formatter: dmt_formatter
      level: DEBUG
      mode: 'w'
      filename: dmt.log

loggers:
  dmt_logger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
