version: 1

formatters:
  console_formatter:
    format: '%(asctime)s - %(filename)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M'
  file_formatter:
    format: '%(asctime)s - %(filename)s - %(funcName)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console_formatter
    stream: ext://sys.stdout
  file:
      class : logging.handlers.RotatingFileHandler
      formatter: file_formatter
      level: TRACE
      filename: dmt.log
      mode: 'w'
      maxBytes: 10485760
      backupCount: 5

loggers:
  dmt_logger:
    level: TRACE
    handlers: [console, file]
    propagate: no